SELECT
	A.PAYCHECK_NBR,
	A.PAGE_NUM,
	A.EMPLID,
	A.EMPL_RCD,
	D.JOBCODE,
	E.DESCR AS JOBCODE_DESCR,
	C.POSITION_NBR,
	D.DESCR AS POSN_DESCR,
	D.UNION_CD,
	F.DESCR AS UNION_DESCR,
	F.BARG_UNIT,
	G.DESCR AS BARG_UNIT_DESCR,
	A.BUSINESS_UNIT,
	A.DEPTID,
	B.DESCR,
	A.NAME,
	A.PAYCHECK_NAME,
	A.COMPANY,
	A.PAYGROUP,
	H.DESCR AS PAYGRP_DESCR,
	A.PAY_END_DT,
	A.CHECK_DT,
	A.PAYCHECK_NBR,
	(CASE
	WHEN A.EMPL_TYPE = 'S' THEN 'SALARY'
	WHEN A.EMPL_TYPE = 'H' THEN 'HOURLY'
	ELSE ''
	END) AS EMPLOYEE_TYPE,
	A.TOTAL_GROSS,
	C.ERNCD,
	C.EARNINGS,
	A.TOTAL_TAXES,
	A.TOTAL_DEDUCTIONS,
	A.NET_PAY,
	J.ERNCD AS OTH_EARNS,
	J.OTH_EARNS,
	J.OTH_HRS
FROM
	PS_PAY_CHECK A
	LEFT JOIN PS_DEPT_TBL B
	ON A.DEPTID = B.DEPTID
		AND B.EFFDT =
			(SELECT MAX(B2.EFFDT)
			FROM PS_DEPT_TBL B2
			WHERE B2.DEPTID = B.DEPTID
			AND B2.DML_IND <> 'D'
			AND B2.EFFDT <= GETDATE())
		AND B.DML_IND <> 'D'
	LEFT JOIN PS_PAY_CHECK_EARNS C
		ON A.COMPANY = C.COMPANY
		AND A.PAYGROUP = C.PAYGROUP
		AND A.PAY_END_DT = C.PAY_END_DT
		AND A.OFF_CYCLE = C.OFF_CYCLE
		AND A.PAGE_NUM = C.PAGE_NUM
		AND A.LINE_NUM = C.LINE_NUM
		AND A.SEPCHK = C.SEPCHK
		AND C.DML_IND <> 'D'
	LEFT JOIN PS_POSITION_DATA D
		ON C.POSITION_NBR = D.POSITION_NBR
		AND C.BUSINESS_UNIT = D.BUSINESS_UNIT
			AND D.EFFDT =
				(SELECT MAX(D2.EFFDT)
				FROM PS_POSITION_DATA D2
				WHERE D2.POSITION_NBR = D.POSITION_NBR
				AND D2.BUSINESS_UNIT = D.BUSINESS_UNIT
				AND D2.DML_IND <> 'D'
				AND D2.EFFDT <= GETDATE())
		AND D.DML_IND <> 'D'
	LEFT JOIN PS_JOBCODE_TBL E
		ON D.JOBCODE = E.JOBCODE
			AND E.EFFDT =
				(SELECT MAX(E2.EFFDT)
				FROM PS_JOBCODE_TBL E2
				WHERE E2.JOBCODE = E.JOBCODE
				AND E2.DML_IND <> 'D'
				AND E2.EFFDT <= GETDATE())
		AND E.DML_IND <> 'D'
	LEFT JOIN PS_UNION_TBL F
		ON D.UNION_CD = F.UNION_CD
			AND F.EFFDT = 
				(SELECT MAX(F2.EFFDT)
				FROM PS_UNION_TBL F2
				WHERE F2.UNION_CD = F.UNION_CD
				AND F2.DML_IND <> 'D'
				AND F2.EFFDT <= GETDATE())
		AND F.DML_IND <> 'D'
	LEFT JOIN PS_HR_BARG_UNIT G
		ON F.BARG_UNIT = G.BARG_UNIT
			AND G.EFFDT =
				(SELECT MAX(G2.EFFDT)
				FROM PS_HR_BARG_UNIT G2
				WHERE G2.BARG_UNIT = G.BARG_UNIT
				AND G2.DML_IND <> 'D'
				AND G2.EFFDT <= GETDATE())
		AND G.DML_IND <> 'D'
	LEFT JOIN PS_PAYGROUP_TBL H
		ON A.PAYGROUP = H.PAYGROUP
			AND H.EFFDT = 
				(SELECT MAX(H2.EFFDT)
				FROM PS_PAYGROUP_TBL H2
				WHERE H2.PAYGROUP = H.PAYGROUP
				AND H2.DML_IND <> 'D'
				AND H2.EFFDT <= GETDATE())
	LEFT JOIN PS_EARNINGS_TBL I
		ON I.ERNCD = C.ERNCD
			AND I.EFFDT =
				(SELECT MAX(I2.EFFDT)
				FROM PS_EARNINGS_TBL I2
				WHERE I2.ERNCD = I.ERNCD
				AND I2.DML_IND <> 'D'
				AND I2.EFFDT <= GETDATE())	
	LEFT JOIN PS_PAY_OTH_EARNS J
		ON A.COMPANY = J.COMPANY
		AND A.PAYGROUP = J.PAYGROUP
		AND A.PAY_END_DT = J.PAY_END_DT
		AND A.OFF_CYCLE = J.OFF_CYCLE
		AND A.PAGE_NUM = J.PAGE_NUM
		AND A.LINE_NUM = J.LINE_NUM
		AND A.SEPCHK = J.SEPCHK
		AND J.DML_IND <> 'D'
WHERE
	A.DML_IND <> 'D'
	AND A.NAME = A.PAYCHECK_NAME
	AND A.PAY_END_DT = '2020-05-31'
--	AND A.EMPLID = 10049261
GROUP BY
	A.PAYCHECK_NBR,
	A.PAGE_NUM,
	A.EMPLID,
	A.EMPL_RCD,
	D.JOBCODE,
	E.DESCR,
	C.POSITION_NBR,
	D.DESCR,
	D.UNION_CD,
	F.DESCR,
	F.BARG_UNIT,
	G.DESCR,
	A.BUSINESS_UNIT,
	A.DEPTID,
	B.DESCR,
	A.NAME,
	A.PAYCHECK_NAME,
	A.COMPANY,
	A.PAYGROUP,
	H.DESCR,
	A.PAY_END_DT,
	A.CHECK_DT,
	A.PAYCHECK_NBR,
	(CASE
	WHEN A.EMPL_TYPE = 'S' THEN 'SALARY'
	WHEN A.EMPL_TYPE = 'H' THEN 'HOURLY'
	ELSE ''
	END),
	A.TOTAL_GROSS,
	C.ERNCD,
	C.EARNINGS,
	A.TOTAL_TAXES,
	A.TOTAL_DEDUCTIONS,
	A.NET_PAY,
	J.ERNCD,
	J.OTH_EARNS,
	J.OTH_HRS;

SELECT TOP 10 * FROM PS_UNION_TBL;
SELECT TOP 10 * FROM PS_PAYGROUP_TBL WHERE PAYGROUP = 'MB7'

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME LIKE '%BARG%'
SELECT * FROM PS_HR_BARG_UNIT

SELECT * FROM PS_POSITION_DATA WHERE 