SELECT
	A.EMPLID,
	H.UC_EXT_SYSTEM_ID,
	B.EMAIL_ADDR,
	G.NAME,
	A.EMPL_RCD,
	A.EFFDT,
	A.EFFSEQ,
	A.PER_ORG,
	A.DEPTID,
	C.DESCR,
	A.JOBCODE,
	I.DESCR AS 'JOBCODE_DESCR',
	A.POSITION_NBR,
	J.DESCR AS 'POSITION_DESCR',
	A.SUPERVISOR_ID,
	(CASE
	WHEN A.HR_STATUS = 'A' THEN 'ACTIVE'
	WHEN A.HR_STATUS = 'I' THEN 'INACTIVE'
	ELSE ''
	END),
	A.POSITION_OVERRIDE,
	A.POSN_CHANGE_RECORD,
	(CASE
	WHEN A.EMPL_STATUS = 'A' THEN 'ACTIVE'
	WHEN A.EMPL_STATUS = 'D' THEN 'DECEASED'
	WHEN A.EMPL_STATUS = 'L' THEN 'UNPAID LEAVE OF ABSENCE'
	WHEN A.EMPL_STATUS = 'P' THEN 'PAID LEAVE OF ABSENCE'
	WHEN A.EMPL_STATUS = 'R' THEN 'RETIRED'
	WHEN A.EMPL_STATUS = 'T' THEN 'TERMINATED'
	WHEN A.EMPL_STATUS = 'W' THEN 'SHORT WORK BREAK'
	ELSE ''
	END) AS 'PAYROLL_STATUS',
	A.ACTION,
	E.ACTION_DESCR,
	A.ACTION_DT,
	A.ACTION_REASON,
	F.DESCR AS 'ACTN_REASN_DESCR',
	A.LOCATION,
	A.TAX_LOCATION_CD,
	A.JOB_ENTRY_DT,
	A.DEPT_ENTRY_DT,
	A.POSITION_ENTRY_DT,
	A.SHIFT,
	A.REG_TEMP,
	A.FULL_PART_TIME,
	A.COMPANY,
	A.PAYGROUP,
	D.DESCR AS 'PAYGRP_DESCR',
	A.BAS_GROUP_ID,
	R.DESCR,
	A.ELIG_CONFIG1,
	A.ELIG_CONFIG2,
	A.ELIG_CONFIG3,
	A.ELIG_CONFIG4,
	A.ELIG_CONFIG5,
	A.ELIG_CONFIG6,
	A.ELIG_CONFIG7,
	A.ELIG_CONFIG8,
	A.ELIG_CONFIG9,
	A.BEN_STATUS,
	A.BAS_ACTION,
	A.COBRA_ACTION,
	A.EMPL_TYPE,
	(CASE
		WHEN A.EMPL_TYPE = 'S' THEN 'SALARY'
		WHEN A.EMPL_TYPE = 'H' THEN 'HOURLY'
		ELSE ''
	END) AS 'EMPL_TYPE_DESCR',
	A.HOLIDAY_SCHEDULE,
	A.STD_HOURS,
	A.STD_HRS_FREQUENCY,
	A.OFFICER_CD,
	A.EMPL_CLASS,
	L.DESCR AS 'EMPL_CLASS_DESCR',
	A.SAL_ADMIN_PLAN,
	M.DESCR AS 'SAL_ADMIN_PLAN_DESCR',
	A.GRADE,
	N.DESCR AS 'GRADE_DESCR',
	A.GRADE_ENTRY_DT,
	A.STEP,
	O.STEP_DESCR,
	A.STEP_ENTRY_DT,
	A.EARNS_DIST_TYPE,
	A.COMP_FREQUENCY,
	A.COMPRATE,
	A.CHANGE_AMT,
	A.CHANGE_PCT,
	A.ANNUAL_RT,
	A.MONTHLY_RT,
	A.DAILY_RT,
	A.HOURLY_RT,
	A.ANNL_BENEF_BASE_RT,
	A.SHIFT_RT,
	A.SHIFT_FACTOR,
	A.CURRENCY_CD,
	A.BUSINESS_UNIT,
	Q.DESCR ,
	A.SETID_DEPT,
	A.SETID_JOBCODE,
	A.SETID_LOCATION,
	A.SETID_SALARY,
	A.SETID_EMPL_CLASS,
	A.REG_REGION,
	A.DIRECTLY_TIPPED,
	A.FLSA_STATUS,
	A.EEO_CLASS,
	A.UNION_CD,
	P.DESCR AS 'UNION_CD_DESCR',
	A.BARG_UNIT,
	A.UNION_SENIORITY_DT,
	A.GP_PAYGROUP,
	A.GP_DFLT_ELIG_GRP,
	A.GP_ELIG_GRP,
	A.GP_DFLT_CURRTTYP,
	A.CUR_RT_TYPE,
	A.GP_DFLT_EXRTDT,
	A.GP_ASOF_DT_EXG_RT,
	A.CLASS_INDC,
	A.ENCUMB_OVERRIDE,
	A.FICA_STATUS_EE,
	A.FTE,
	A.PRORATE_CNT_AMT,
	A.PAY_SYSTEM_FLG,
	A.LUMP_SUM_PAY,
	A.CONTRACT_NUM,
	A.JOB_INDICATOR,
	A.BENEFIT_SYSTEM,
	A.WORK_DAY_HOURS,
	A.REPORTS_TO,
	JJ.DESCR,
	A.JOB_DATA_SRC_CD,
	A.ESTABID,
	A.SUPV_LVL_ID,
	A.SETID_SUPV_LVL,
	A.ABSENCE_SYSTEM_CD,
	A.POI_TYPE,
	A.HIRE_DT,
	A.LAST_HIRE_DT,
	A.TERMINATION_DT,
	A.ASGN_START_DT,
	A.LST_ASGN_START_DT,
	A.ASGN_END_DT,
	A.LDW_OVR,
	A.LAST_DATE_WORKED,
	A.EXPECTED_RETURN_DT,
	A.EXPECTED_END_DATE,
	A.AUTO_END_FLG
FROM 
	PS_JOB A
	LEFT JOIN PS_EMAIL_ADDRESSES B
		ON B.EMPLID = A.EMPLID
	LEFT JOIN PS_DEPT_TBL C
		ON C.DEPTID = A.DEPTID
			AND C.EFFDT =
				(SELECT MAX(C2.EFFDT)
				FROM PS_DEPT_TBL C2
				WHERE C2.DEPTID = C.DEPTID
				AND C2.SETID IN ('LACMP','LAMED')
				AND C2.DML_IND <> 'D'
				AND C2.EFFDT <= GETDATE())
	LEFT JOIN PS_PAYGROUP_TBL D
		ON D.PAYGROUP = A.PAYGROUP
			AND D.EFFDT =
				(SELECT MAX(D2.EFFDT)
				FROM PS_PAYGROUP_TBL D2
				WHERE D2.PAYGROUP = D.PAYGROUP
				AND D2.DML_IND <> 'D'
				AND D2.EFFDT <= GETDATE())
	LEFT JOIN PS_ACTION_TBL E
		ON E.ACTION = A.ACTION
			AND E.EFFDT =
				(SELECT MAX(E2.EFFDT)
				FROM PS_ACTION_TBL E2
				WHERE E2.ACTION = E.ACTION
				AND E2.DML_IND <> 'D'
				AND E2.EFFDT <= GETDATE())
	LEFT JOIN PS_ACTN_REASON_TBL F
		ON F.ACTION = A.ACTION
		AND F.ACTION_REASON = A.ACTION_REASON
			AND F.EFFDT =
				(SELECT MAX(F2.EFFDT)
				FROM PS_ACTN_REASON_TBL F2
				WHERE F2.ACTION = F.ACTION
				AND F2.ACTION_REASON = F.ACTION_REASON
				AND F2.DML_IND <> 'D'
				AND F2.EFFDT <= GETDATE())
	LEFT JOIN PS_NAMES G
		ON G.EMPLID = A.EMPLID
			AND G.EFFDT =
				(SELECT MAX(G2.EFFDT)
				FROM PS_NAMES G2
				WHERE G2.EMPLID = G.EMPLID
				AND G2.DML_IND = G.DML_IND
				AND G2.NAME_TYPE = 'PRI'
				AND G2.EFFDT <= GETDATE())
	LEFT JOIN PS_UC_EXT_SYSTEM H
		ON H.EMPLID = A.EMPLID
			AND H.EFFDT =
				(SELECT MAX(H2.EFFDT)
				FROM PS_UC_EXT_SYSTEM H2
				WHERE H2.EMPLID = H.EMPLID
				AND H2.DML_IND <> 'D'
				AND H2.UC_EXT_SYSTEM = 'UCLA_UID'
				AND H2.EFFDT <= GETDATE())
	LEFT JOIN PS_JOBCODE_TBL I
		ON I.JOBCODE = A.JOBCODE
			AND I.EFFDT =
				(SELECT MAX(I2.EFFDT)
				FROM PS_JOBCODE_TBL I2
				WHERE I2.JOBCODE = I.JOBCODE
				AND I2.DML_IND <> 'D'
				AND I2.EFFDT <= GETDATE())
	LEFT JOIN PS_POSITION_DATA J
		ON J.POSITION_NBR = A.POSITION_NBR
			AND J.EFFDT =
				(SELECT MAX(J2.EFFDT)
				FROM PS_POSITION_DATA J2
				WHERE J2.POSITION_NBR = J.POSITION_NBR
				AND J2.BUSINESS_UNIT IN ('LACMP','LAMED')
				AND J2.DML_IND <> 'D'
				AND J2.EFFDT <= GETDATE())
	LEFT JOIN PS_EMPL_CLASS_TBL L
		ON L.EMPL_CLASS = A.EMPL_CLASS
			AND L.EFFDT =
				(SELECT MAX(L2.EFFDT)
				FROM PS_EMPL_CLASS_TBL L2
				WHERE L2.EMPL_CLASS = L.EMPL_CLASS
				AND L2.DML_IND <> 'D'
				AND L2.EFFDT <= GETDATE())
	LEFT JOIN PS_SAL_PLAN_TBL M
		ON M.SAL_ADMIN_PLAN = A.SAL_ADMIN_PLAN
			AND M.EFFDT =
				(SELECT MAX(M2.EFFDT)
				FROM PS_SAL_PLAN_TBL M2
				WHERE M2.SAL_ADMIN_PLAN = M.SAL_ADMIN_PLAN
				AND M2.DML_IND <> 'D'
				AND M2.EFFDT <= GETDATE())
	LEFT JOIN PS_SAL_GRADE_TBL N
		ON N.SETID = A.BUSINESS_UNIT
		AND N.SAL_ADMIN_PLAN = A.SAL_ADMIN_PLAN
		AND N.GRADE = A.GRADE
			AND N.EFFDT = 
				(SELECT MAX(N2.EFFDT)
				FROM PS_SAL_GRADE_TBL N2
				WHERE N2.SAL_ADMIN_PLAN = N.SAL_ADMIN_PLAN
				AND N2.SETID = N.SETID
				AND N2.GRADE = N.GRADE
				AND N2.SETID IN ('LACMP','LAMED')
				AND N2.DML_IND <> 'D'
				AND N2.EFFDT <= GETDATE())
	LEFT JOIN PS_SAL_STEP_TBL O
		ON O.SAL_ADMIN_PLAN = A.SAL_ADMIN_PLAN
		AND O.GRADE = A.GRADE
		AND O.STEP = A.STEP
		AND O.SETID = A.BUSINESS_UNIT
			AND O.EFFDT =
				(SELECT MAX(O2.EFFDT)
				FROM PS_SAL_STEP_TBL O2
				WHERE O2.SAL_ADMIN_PLAN = O.SAL_ADMIN_PLAN
				AND O2.SETID = O.SETID
				AND O2.GRADE = O.GRADE
				AND O2.STEP = O.STEP
				AND O2.DML_IND <> 'D'
				AND O2.SETID IN ('LACMP','LAMED')
				AND O2.EFFDT <= GETDATE())
	LEFT JOIN PS_UNION_TBL P
	ON P.UNION_CD = A.UNION_CD
		AND P.EFFDT =
			(SELECT MAX(P2.EFFDT)
			FROM PS_UNION_TBL P2
			WHERE P2.UNION_CD = P.UNION_CD
			AND P2.DML_IND <> 'D'
			AND P2.EFFDT <= GETDATE())
	LEFT JOIN PS_POSITION_DATA JJ
		ON JJ.POSITION_NBR = A.REPORTS_TO
			AND JJ.EFFDT =
				(SELECT MAX(JJ2.EFFDT)
				FROM PS_POSITION_DATA JJ2
				WHERE JJ2.POSITION_NBR = JJ.POSITION_NBR
				AND JJ2.BUSINESS_UNIT IN ('LACMP','LAMED')
				AND JJ2.DML_IND <> 'D'
				AND JJ2.EFFDT <= GETDATE())
	LEFT JOIN PS_BUS_UNIT_TBL_HR Q
		ON Q.BUSINESS_UNIT = A.BUSINESS_UNIT
		AND Q.ACTIVE_INACTIVE = 'A'
	LEFT JOIN PS_BAS_GROUP_TBL R
		ON R.BAS_GROUP_ID = A.BAS_GROUP_ID
WHERE
	A.EFFDT =
		(SELECT MAX(A2.EFFDT)
		FROM PS_JOB A2
		WHERE A2.EMPLID = A.EMPLID
		AND A2.DML_IND <> 'D'
		AND A2.EFFDT <= GETDATE())
	AND A.EFFSEQ =
		(SELECT MAX(A3.EFFSEQ)
		FROM PS_JOB A3
		WHERE A3.EMPLID = A.EMPLID
		AND A3.DML_IND <> 'D'
		AND A3.EFFDT = A.EFFDT)
	AND A.DML_IND <> 'D'
	AND B.DML_IND <> 'D'
	AND C.DML_IND <> 'D'
	AND D.DML_IND <> 'D'
	AND E.DML_IND <> 'D'
	AND F.DML_IND <> 'D'
	AND G.DML_IND <> 'D'
	AND H.DML_IND <> 'D'
	AND I.DML_IND <> 'D'
	AND J.DML_IND <> 'D'
	AND L.DML_IND <> 'D'
	AND M.DML_IND <> 'D'
	AND N.DML_IND <> 'D'
	AND P.DML_IND <> 'D'
	AND JJ.DML_IND <> 'D'
	AND Q.DML_IND <> 'D'
	AND R.DML_IND <> 'D'
	AND A.EMPL_STATUS NOT IN ('D','R','T')
	AND A.JOB_INDICATOR = 'P'
	AND B.PREF_EMAIL_FLAG = 'Y'
	AND A.BUSINESS_UNIT IN ('LACMP','LAMED')
	AND C.SETID IN ('LACMP','LAMED')
	AND G.NAME_TYPE = 'PRI'
	AND H.UC_EXT_SYSTEM = 'UCLA_UID'
	AND J.BUSINESS_UNIT IN ('LACMP','LAMED')
	AND JJ.BUSINESS_UNIT IN ('LACMP','LAMED')
--	AND A.EMPLID IN
--	(
--	10262694
--	)
	AND A.DEPTID IN
	(
	'352500'
	)
GROUP BY
	A.EMPLID,
	H.UC_EXT_SYSTEM_ID,
	B.EMAIL_ADDR,
	G.NAME,
	A.EMPL_RCD,
	A.EFFDT,
	A.EFFSEQ,
	A.PER_ORG,
	A.DEPTID,
	C.DESCR,
	A.JOBCODE,
	I.DESCR,
	A.POSITION_NBR,
	J.DESCR,
	J.REPORTS_TO,
	A.SUPERVISOR_ID,
	A.HR_STATUS,
	A.POSITION_OVERRIDE,
	A.POSN_CHANGE_RECORD,
	A.EMPL_STATUS,
	A.ACTION,
	E.ACTION_DESCR,
	A.ACTION_DT,
	A.ACTION_REASON,
	F.DESCR,
	A.LOCATION,
	A.TAX_LOCATION_CD,
	A.JOB_ENTRY_DT,
	A.DEPT_ENTRY_DT,
	A.POSITION_ENTRY_DT,
	A.SHIFT,
	A.REG_TEMP,
	A.FULL_PART_TIME,
	A.COMPANY,
	A.PAYGROUP,
	D.DESCR,
	A.BAS_GROUP_ID,
	A.ELIG_CONFIG1,
	A.ELIG_CONFIG2,
	A.ELIG_CONFIG3,
	A.ELIG_CONFIG4,
	A.ELIG_CONFIG5,
	A.ELIG_CONFIG6,
	A.ELIG_CONFIG7,
	A.ELIG_CONFIG8,
	A.ELIG_CONFIG9,
	A.BEN_STATUS,
	A.BAS_ACTION,
	R.DESCR,
	A.COBRA_ACTION,
	A.EMPL_TYPE,
	A.HOLIDAY_SCHEDULE,
	A.STD_HOURS,
	A.STD_HRS_FREQUENCY,
	A.OFFICER_CD,
	A.EMPL_CLASS,
	L.DESCR,
	A.SAL_ADMIN_PLAN,
	M.DESCR,
	A.GRADE,
	N.DESCR,
	A.GRADE_ENTRY_DT,
	A.STEP,
	O.STEP_DESCR,
	A.STEP_ENTRY_DT,
	A.EARNS_DIST_TYPE,
	A.COMP_FREQUENCY,
	A.COMPRATE,
	A.CHANGE_AMT,
	A.CHANGE_PCT,
	A.ANNUAL_RT,
	A.MONTHLY_RT,
	A.DAILY_RT,
	A.HOURLY_RT,
	A.ANNL_BENEF_BASE_RT,
	A.SHIFT_RT,
	A.SHIFT_FACTOR,
	A.CURRENCY_CD,
	A.BUSINESS_UNIT,
	Q.DESCR,
	A.SETID_DEPT,
	A.SETID_JOBCODE,
	A.SETID_LOCATION,
	A.SETID_SALARY,
	A.SETID_EMPL_CLASS,
	A.REG_REGION,
	A.DIRECTLY_TIPPED,
	A.FLSA_STATUS,
	A.EEO_CLASS,
	A.UNION_CD,
	P.DESCR,
	A.BARG_UNIT,
	A.UNION_SENIORITY_DT,
	A.GP_PAYGROUP,
	A.GP_DFLT_ELIG_GRP,
	A.GP_ELIG_GRP,
	A.GP_DFLT_CURRTTYP,
	A.CUR_RT_TYPE,
	A.GP_DFLT_EXRTDT,
	A.GP_ASOF_DT_EXG_RT,
	A.CLASS_INDC,
	A.ENCUMB_OVERRIDE,
	A.FICA_STATUS_EE,
	A.FTE,
	A.PRORATE_CNT_AMT,
	A.PAY_SYSTEM_FLG,
	A.LUMP_SUM_PAY,
	A.CONTRACT_NUM,
	A.JOB_INDICATOR,
	A.BENEFIT_SYSTEM,
	A.WORK_DAY_HOURS,
	A.REPORTS_TO,
	JJ.DESCR,
	A.JOB_DATA_SRC_CD,
	A.ESTABID,
	A.SUPV_LVL_ID,
	A.SETID_SUPV_LVL,
	A.ABSENCE_SYSTEM_CD,
	A.POI_TYPE,
	A.HIRE_DT,
	A.LAST_HIRE_DT,
	A.TERMINATION_DT,
	A.ASGN_START_DT,
	A.LST_ASGN_START_DT,
	A.ASGN_END_DT,
	A.LDW_OVR,
	A.LAST_DATE_WORKED,
	A.EXPECTED_RETURN_DT,
	A.EXPECTED_END_DATE,
	A.AUTO_END_FLG
ORDER BY
	A.EMPLID
ASC