SELECT
	A.EMPLID,
	A.EMPL_RCD,
    B.NAME,
	CONCAT(A.EMPLID,' ',A.EMPL_RCD) AS EMPLID_CONCAT,
	A.EFFDT,
    A.DEPTID,
	A.HR_STATUS,
    A.EMPL_STATUS,
    A.UNION_CD,
    A.POSITION_NBR
FROM
	PS_JOB A
    LEFT JOIN PS_NAMES B
    ON B.EMPLID = A.EMPLID
    AND B.DML_IND <> 'D'
    AND B.NAME_TYPE = 'PRI'
    AND B.EFFDT =
        (SELECT MAX(B2.EFFDT)
        FROM PS_NAMES B2
        WHERE B2.EMPLID = B.EMPLID
        AND B2.DML_IND <> 'D'
        AND B2.NAME_TYPE = 'PRI'
        AND B2.EFFDT <= GETDATE())
WHERE
	A.DML_IND <> 'D'
	AND CONCAT(A.EMPLID,' ',A.EMPL_RCD) IN ('10123512 0')
	AND A.EFFDT = 
		(SELECT MAX(A2.EFFDT) 
		FROM PS_JOB A2 
		WHERE A2.EMPLID = A.EMPLID 
		AND A2.EMPL_RCD = A.EMPL_RCD 
		AND A2.DML_IND <> 'D' 
		AND A2.EFFDT <= GETDATE())
	AND A.EFFSEQ = 
		(SELECT MAX(A3.EFFSEQ) 
		FROM PS_JOB A3 
		WHERE A3.EMPLID = A.EMPLID 
		AND A3.EMPL_RCD = A.EMPL_RCD 
		AND A3.DML_IND <> 'D' 
		AND A3.EFFDT = A.EFFDT)
GROUP BY
	A.EMPLID,
	A.EMPL_RCD,
    B.NAME,
	CONCAT(A.EMPLID,' ',A.EMPL_RCD),
	A.EFFDT,
	A.DEPTID,
	A.HR_STATUS,
    A.EMPL_STATUS,
    A.UNION_CD,
    A.POSITION_NBR